preload = ~/Pictures/wallpapers/pc/pic.png                                                                                          
wallpaper = DP-1,~/Pictures/wallpapers/pc/pic.png                                                                                   
wallpaper = HDMI-A-1,~/Pictures/wallpapers/pc/pic.png                                                                                   
splash = false                                                                                                                                 
ipc = off
