preload = ~/Pictures/wallpapers/pc/bleb.png
wallpaper = DP-1,~/Pictures/wallpapers/pc/bleb.png
wallpaper = HDMI-A-1,~/Pictures/wallpapers/pc/bleb.png
splash = false                                                                                                                                 
ipc = off
