temperature = 4000      # Цветовая температура, когда включено
transition_time = 5     # Плавность перехода в секундах

on_time = 21:00          # Когда ВКЛЮЧАТЬ ночной режим
off_time = 07:00         # Когда ВЫКЛЮЧАТЬ ночной режим

