preload = ~/Pictures/wallpapers/pc/nature_wallpaper2.jpg
wallpaper = DP-1,~/Pictures/wallpapers/pc/nature_wallpaper2.jpg
wallpaper = HDMI-A-1,~/Pictures/wallpapers/pc/nature_wallpaper2.jpg
splash = false                                                                                                                                 
ipc = off
