# Autostart

exec-once = hypridle # Idle
exec-once = waypaper --restore # Wallpaper and Waybar
exec-once = hyprsunset --temperature 6000
exec-once = swaync # Notifications
# exec-once = udiskie # Manage removable media like flash drives
# exec-once = nm-applet # Wifi
# exec-once = hyprctl setcursor HyprBibataModernClassicSVG 18
# exec-once = gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Classic"
exec-once = waybar
exec-once = wal -R
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = coolercontrold
