# Autostart
exec-once = hypridle
exec-once = hyprpaper 
exec-once = hyprsunset --temperature 6000
exec-once = swaync # Notifications
exec-once = waybar &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = coolercontrold
