general {
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    col.active_border = rgba(668888ee) rgba(aaaaaaee) 45deg
    col.inactive_border = rgba(262626ee)
    
    resize_on_border = false

    layout = dwindle 

    allow_tearing = false
}


decoration {
    rounding = 0

    blur {
        enabled = true
        size = 3
        passes = 6
        #vibrancy = 0.1696
    }
}
